### ISSUE TITLE
Add an optional database arguments to CLI migrator

### ISSUE THREAD

**Issue by dedenbangkit** [akvo/Akvo-ResponseGrouper#12]
# Migrate

- By default, pick it from `$DATABASE_URL`
- Optional argument `--database` or `-d`.
- Change `--drop` to `-q`

# Refresh (For cron job)

- Refresh the materialized view with `akvo-responsegrouper -r` or `akvo-responsegrouper --refresh`, the Fn is here: https://github.com/akvo/Akvo-ResponseGrouper/blob/302346314e2ba9a97dbd63d4e1322ac83b24c5de/src/AkvoResponseGrouper/views.py#L64-L66

**Comment by joycarpediem** [comment]
@navins94 , can you please test this and close if this works . Check with Iwan how to test if not clear

**Comment by ifirmawan** [comment]
run the command bellow
```
akvo-responsegrouper --config $(echo "./source/${INSTANCE_NAME}/category.json") --database $(echo $DATABASE_URL | sed 's/-/_/g')
```

**Comment by navins94** [comment]
Hi @joycarpediem I tested this with the help of @ifirmawan. Did not find any issue was able to run successfully
