### ISSUE TITLE
Collection route

### ISSUE THREAD

**Issue by ifirmawan** [akvo/Akvo-ResponseGrouper#5]
Trying to add routes that can access the library

**Comment by dedenbangkit** [comment]
We also need:

Endpoint: "/collection/category/<form_id>" (Path Params)

```json
[{
   "category": "category_name",
   "options": [{
        "name": "option_1",
        "count": 4
   }]
}]
```

**Comment by ifirmawan** [comment]
<img width="1066" alt="Screenshot 2023-01-17 at 08 57 06" src="https://user-images.githubusercontent.com/20871229/212793018-d94b6101-0aa4-4652-87f4-c70791e95af4.png">

using URL collection directly apparently causes the auto redirect to another server (from port 3000 to 5000)

<img width="1137" alt="Screenshot 2023-01-17 at 08 56 49" src="https://user-images.githubusercontent.com/20871229/212793319-756b57c4-cd2d-44fa-a01b-b3edfec0596a.png">

while endpoint categories are returned as before
